defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_ib_policy   
    - ../base/policy@policy: spatial_fuse
    - ../base/train@train: partial_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

experiment_dir: ???

# logging
dry_run: False
debug: False

wandb:
    use_wandb: true
    project: cortexbench_trifinger_${policy.embedding_type}_${ft_method}
    name: trifinger_spatial_fuse_${env.task_name}_${algo.algorithm}_demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}_${now:%m%d}_${now:%H%M}_seed${train.seed}
    group: trifinger_${env.task_name}_${algo.algorithm}
    dir: ./wandb/cortexbench/${ft_method}_spatial_fuse/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}

hydra:
    run:
        dir: ./outputs/cortexbench/${ft_method}_spatial_fuse/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/cortexbench/${ft_method}_spatial_fuse/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}
