defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_ib_policy   
    - ../base/policy@policy: temporal_fuse
    - ../base/train@train: full_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

experiment_dir: ???

# logging
dry_run: False
debug: False

wandb:
    use_wandb: true
    project: cortexbench_${env.env_name}_${policy.embedding_type}_${train.ft_method}
    name: ${env.env_name}_${policy.fuse_method}_${env.task_name}_${algo.algorithm}_demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}_${now:%m%d}_${now:%m%d}_${now:%H%M}_seed${train.seed}
    group: ${env.env_name}_${env.task_name}_${algo.algorithm}
    dir: ./wandb/cortexbench/${train.ft_method}_${policy.fuse_method}/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}

hydra:
    run:
        dir: ./outputs/cortexbench/${train.ft_method}_${policy.fuse_method}/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/cortexbench/${train.ft_method}_${policy.fuse_method}/${algo.algorithm}/${policy.embedding_type}/${env.env_name}/${env.task_name}/demo${data.num_demos}_scale${train.mi_loss_scale}_${train.mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

