defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_ib_policy   
    - ../base/policy@policy: spatial_fuse
    - ../base/train@train: partial_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

exp_notes: Access DMC envs using the dmc2gym package. Experts trained with DDPG from URLB.

algorithm: bc_ib_policy
ft_method: partial_ft
experiment_dir: ???

# logging
dry_run: False
debug: False

hydra:
    run:
        dir: ./outputs/tmp/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/dmcontrol/${env.task_name}/demo${data.num_demos}_demo${data.num_demos}_scale${mi_loss_scale}_${mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/tmp/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/dmcontrol/${env.task_name}/demo${data.num_demos}_demo${data.num_demos}_scale${mi_loss_scale}_${mine_mi_loss_scale}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

mi_loss_scale: 0.005
mine_mi_loss_scale: 0.1