embedding_type: VC1
embedding: vc1_vitb                     # choice of embedding network
embedding_dim: 768
embedding_dir: ???

fuse_method: spatial_fuse
use_spatial: True
spatial_fuse:
    fuse_method: 'sub_cat'
    mlp_layer_dim: [1, 0.5, 0.5, 1]

extra_states_encoder:
    input_size: 0
    output_size: 0
    
policy_head:
    hidden_size: 512
    output_size: ${data.action_dim}
    num_layers: 2