defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_policy   
    - ../base/policy@policy: temporal_fuse
    - ../base/train@train: full_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

algorithm: bc_policy
ft_method: full_ft
experiment_dir: ???

# logging
dry_run: False
debug: False

hydra:
    run:
        dir: ./outputs/tmp/cortexbench/${ft_method}_temporal_fuse/${algorithm}/${policy.embedding_type}/metaworld/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/tmp/cortexbench/${ft_method}_temporal_fuse/${algorithm}/${policy.embedding_type}/metaworld/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

mi_loss_scale: 0.005
mine_mi_loss_scale: 0.1
