defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_policy   
    - ../base/policy@policy: spatial_fuse
    - ../base/train@train: partial_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

algorithm: bc_policy
ft_method: partial_ft
experiment_dir: ???

# logging
dry_run: False
debug: False

wandb:
    use_wandb: true
    project: cortexbench_metaworld_${policy.embedding_type}_${ft_method}
    name: metaworld_spatial_fuse_${env.task_name}_${algorithm}_demo${data.num_demos}_${now:%m%d}_${now:%H%M}_seed${train.seed}
    group: metaworld_${env.task_name}_${algorithm}
    dir: ./wandb/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/metaworld/${env.task_name}/demo${data.num_demos}

hydra:
    run:
        dir: ./outputs/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/metaworld/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/metaworld/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

mi_loss_scale: 0.005
mine_mi_loss_scale: 0.1
