defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_policy   
    - ../base/policy@policy: spatial_fuse
    - ../base/train@train: partial_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

algorithm: bc_ib_policy
ft_method: partial_ft
experiment_dir: ???

# logging
dry_run: False
debug: False

hydra:
    run:
        dir: ./outputs/tmp/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/trifinger/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/tmp/cortexbench/${ft_method}_spatial_fuse/${algorithm}/${policy.embedding_type}/trifinger/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

