defaults:
    - _self_
    - ../base/data@data: default
    - ../base/algo@algo: bc_policy   
    - ../base/policy@policy: temporal_fuse
    - ../base/train@train: partial_ft
    - ../base/eval@eval: default
    - ../base/env@env: default

exp_notes: Access DMC envs using the dmc2gym package. Experts trained with DDPG from URLB.

algorithm: bc_policy
ft_method: partial_ft
experiment_dir: ???

# logging
dry_run: False
debug: False

wandb:
    use_wandb: true
    project: cortexbench_dmcontrol_${policy.embedding_type}_${ft_method}-tmp
    name: dmcontrol_temporal_fuse_${env.task_name}_${algorithm}_demo${data.num_demos}_${now:%m%d}_${now:%H%M}_seed${train.seed}
    group: dmcontrol_${env.task_name}_${algorithm}
    dir: ./wandb/tmp/cortexbench/${ft_method}_temporal_fuse/${algorithm}/${policy.embedding_type}/dmcontrol/${env.task_name}/demo${data.num_demos}

hydra:
    run:
        dir: ./outputs/tmp/cortexbench/${ft_method}_temporal_fuse/${algorithm}/${policy.embedding_type}/dmcontrol/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
    sweep:
        dir: ./outputs/tmp/cortexbench/${ft_method}_temporal_fuse/${algorithm}/${policy.embedding_type}/dmcontrol/${env.task_name}/demo${data.num_demos}/${now:%m%d}_${now:%H%M}_seed${train.seed}
        subdir: ${hydra.job.num}

