load_path: "" # only used when separately evaluating a pretrained model
eval: false
debug: false

batch_size: 64
num_workers: 4
eval_every: ${train.save_freq}

# rollout
enable_rollout: false

# other
use_mp: true
num_procs: 20
save_sim_states: false
